# Generated by Django 3.0.2 on 2020-01-31 02:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.DateField(default=datetime.date(1970, 1, 1))),
                ('genre', models.CharField(max_length=255)),
                ('num_of_pages', models.IntegerField(default=0)),
            ],
        ),
    ]
